### ISSUE TITLE
Add some way to update the exits list by scraping a website

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/rita#184]
It would need some sort of signature check but it would be great to be able to update the exits list on the fly.

**Comment by jkilpatr** [comment]
or we could just rely on https, anyways the really difficult part I realize is merging the existing exits list with the new one successfully.

**Comment by donkey-hotei** [comment]
This is solved already? I've been told it's a good idea to move the list of exits in `/etc/rita.toml` to it's own file like to `exits.toml` to avoid cluttering the rita config.
