### ISSUE TITLE
StatsCollector improvements

### ISSUE THREAD

**Issue by mpapierski** [althea-net/rita#220]
StatsCollector has to be improved because it is blocking main reactor with blocking calls.

# Problem

Things that are blocking in StatsCollector:

- Reading from filesystem
  - `KI.get_proc_stat`
  - `KI.get_proc_load_avg`
  - `KI.get_device_stats`
  - `KI.get_route_stats`
  - `KI.get_meminfo_stats`
  - `KI.get_cpuinfo_stats`
- Blocking HTTP request to `stat_server_url`

All of this every 5 seconds possibly blocking other asynchronous operations.

# Solution

- For reading filesystem we can leverage `tokio.threadpool` which has a nice API for making blocking calls asynchronous: https://docs.rs/tokio-threadpool/0.1/tokio_threadpool/fn.blocking.html
- For HTTP request we can also use async API of `reqwest` library, instead of the synchronous one.

**Comment by jkilpatr** [comment]
We should also create a totally separate event loop for this, so that it's failure can't block system essential actions. 

I currently consider this low priority.

**Comment by mpapierski** [comment]
>We should also create a totally separate event loop for this, so that it's failure can't block system essential actions.
>
>I currently consider this low priority.

I agree. And thats how `tokio-threadpool` crate can help us. It maintains internal pool to schedule blocking calls and post results back to our reactor.
