### ISSUE TITLE
Compilation error when building for arm with --features development flag

### ISSUE THREAD

**Issue by asoltys** [althea-net/rita#233]
Trying to build master (e193b15) for my GL-B1300 with the development flag so I can use the /wipe endpoint, I get this:

`error[E0599]: no function or associated item named new found for type actix_web::Path<_> in the current scope
  --> rita/src/rita_common/dashboard/network_endpoints.rs:92:10
   |
92 |         &Path::new(&SETTING.get_network().wg_private_key_path),
   |          ^^^^^^^^^ function or associated item not found in actix_web::Path<_>
[openwrt_build_ipq40xx.txt](https://github.com/althea-mesh/althea_rs/files/2319490/openwrt_build_ipq40xx.txt)

I've attached the build script I'm using. I made modifications on line 5:
source $DIR/build_common.sh --features development

and line 25:
export RUSTFLAGS="-C link-arg=-lgcc"

**Comment by jkilpatr** [comment]
I think this is resolved now?
