### ISSUE TITLE
Bump `lettre` version once the OpenSSL version fix makes it to crates.io

### ISSUE THREAD

**Issue by drozdziak1** [althea-net/rita#276]
# Problem
OpenSSL 1.1.1 just made it to ArchLinux' repos and isn't recognized by `openssl`'s `build.rs`. A tiny dep graph for context:
```plain
rita <- lettre <- native-tls <- openssl
```
The `lettre` crate (provides us with mailing, therefore it's non-negotiable) is using a version of `native-tls` that's using a version of `openssl` which can't recognize OpenSSL 1.1.1

# Solution
[This PR](https://github.com/lettre/lettre/pull/303) bumps the `native-tls` version in `lettre` and needs to be merged in and make it to [crates.io](crates.io) so that we can bump its version in `rita`. Until that happens we're blocked, but in practice it's just a mild annoyance of having to downgrade `openssl` on Arch.

**Comment by mpapierski** [comment]
@drozdziak1 We can always do a patch entry to replace lattre with a github repo? Do you expect that this pull request would be merged anytime soon?
