### ISSUE TITLE
Exit Traffic Watcher is broken and missing traffic freqently 

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/rita#288]
`Sep 26 19:54:50 localhost rita_exit: WARN 2018-09-26T23:54:50Z: rita_exit::rita_common::traffic_watcher: We have an id Identity { mesh_ip: V6(fd86:a371:8952:227f:8062:131b:a844:30ed), eth_address: 0x0101010101010101010101010101010101010101, wg_public_key: "QgZhZhfe6vK+zwIqya+LC1u9fqlYfIFcK/w7p1EWMHo=" } but not destination`

`Sep 27 01:54:49 vps184553 rita_exit: WARN 2018-09-26T23:54:49Z: rita_exit::rita_exit::traffic_watcher: We have a destination Int256(0) but no id`

deadline:11/01/2018

This has been resheduled due to other issues, placing it in the latter half of next week

**Comment by drozdziak1** [comment]
Reevaluation deadline set to **Monday 2018-10-22**
