### ISSUE TITLE
Review KernelInterface direct usage of Command interface

### ISSUE THREAD

**Issue by mpapierski** [althea-net/rita#320]
_Originally posted by @mpapierski in https://github.com/althea-mesh/althea_rs/pull/318_

`test_generate_wg_key` calls wireguard binary while testing, it will be better if we could use KI's wrapper for shelling out. This way the behaviour could be tested.

Ideally we should review which methods in `KernelInterface` does not use Command wrapper and update or add unit tests accordingly.

**Comment by jkilpatr** [comment]
IMO the point of the direct call is that we don't have to test as much because we're using key Rust features.
