### ISSUE TITLE
Evaluate real-time UDP RTT in Rita

### ISSUE THREAD

**Issue by drozdziak1** [althea-net/rita#346]
The HTTP RTT endpoint is wildly unreliable, it would be nice to reincarnate it as a tiny UDP-based request. 

Deadline: determine what to do and try implementing it by **2018-11-13**

**Comment by kingoflolz** [comment]
The biggest cause of latency would likely be from blocking when shelling out, which we don't really plan to phase out in the future, so it may be better to create another reactor and run http on that (http vs udp should not really factor into latency)

**Comment by kingoflolz** [comment]
would need another port open and need firewall changes though

**Comment by jkilpatr** [comment]
we should consider just using udp, the issue is we need some futures trigger on packet receive.

**Comment by jkilpatr** [comment]
also look at the algorithm babel uses for fp rtt reception.
