### ISSUE TITLE
Stop using Stan's fork for num256 in bounty_hunter

### ISSUE THREAD

**Issue by drozdziak1** [althea-net/rita#352]
Due: Monday 2018-11-19.

1. Close this https://github.com/althea-mesh/num256_rs/pull/4
2. Publish new version
3. Change the Cargo.toml entry in bounty_hunter

**Comment by jkilpatr** [comment]
can this be closed now?

**Comment by mpapierski** [comment]
@jkilpatr yes, its merged and released on crates and also the BH pull request uses it now.

**Comment by drozdziak1** [comment]
Yup, it is done, my PR doesn't use the fork either
