### ISSUE TITLE
Http auth to secure dashboard

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/rita#416]
we need both http auth setup in the firmware as well as endpoints ready to change it.

**Comment by jkilpatr** [comment]
https://github.com/althea-mesh/althea_rs/pull/452

The backend code is here, the remaining task is designs and front end implementation. 

@asoltys  I can't really comment on the design but I think the way things should work is that you get asked for a password which is then stored in browser memory hashed and salted before being submitted to the router hashed and salted. You should be able to see if you need to ask for a password or not by checking the info endpoint. 

I don't think we can store the password in a cookie, or if we do we need to detect failure, because you can't tell when you're talking to a new althea router except that the password won't work or won't be needed. So prepare for the situation of the same browser hopping between several althea devices.

**Comment by jtremback** [comment]
Don't do this hashing salting stuff, it's security theatre

**Comment by jtremback** [comment]
First login

![image](https://user-images.githubusercontent.com/1335122/55599103-fd272000-570a-11e9-8aac-2285bad252fc.png)

**Comment by jtremback** [comment]
Subsequent logins

![image](https://user-images.githubusercontent.com/1335122/55599129-1fb93900-570b-11e9-851a-461e17dad377.png)
